:- initialization(main).

main :-
	L1=("a"||.),
	writeq(L1), nl,
	L2=("a"||...),
	writeq(L2), nl,
	L3= ""||'.' ,
	writeq(L3), nl,
	L4= "a"||'b c',
	writeq(L4), nl,
	L5= "a"||"b c" ,
	write_term(stdout,L5,[double_quotes(true)]), nl,
	L6= "abc"||"def",
	write_term(stdout,L6,[double_quotes(true)]), nl,
	L7= ""||"def",
	write_term(stdout,L7,[double_quotes(true)]), nl,
	L8= "abc"||"def"||"ghi",
	write_term(stdout,L8,[double_quotes(true)]), nl,
	L9= ""||""||""||"",
	write_term(stdout,L9,[double_quotes(true)]), nl,
	L10= ""||1.23,
	write_term(stdout,L10,[double_quotes(true)]), nl,
	L11= "a"||"b"||1.23,
	write_term(stdout,L11,[double_quotes(true)]), nl.
